apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-deployment
spec:
  selector:
    matchLabels:
      app: post-pod
  template:
    metadata:
      labels:
        app: post-pod
    spec:
      containers:
      - name: post-container
        image: benhassan98/post-service-image:latest
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: post-service
spec:
  selector:
    app: post-pod
  ports:
  - name: post-service-port
    protocol: TCP
    port: 8080
    targetPort: 8080
                                                                                                                                    
